import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HomeWrapper from "./homeWrapper";
import CartProviderWrapper from "./CartProviderWrapper";
import Navbar from "./(components)/Navbar";
import ProvidersWrapper from "./ProvidersWrapper";
import Footer from "@/app/(components)/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // return (
  //   <html lang="en">
  //     <body className={inter.className}>
  //       {" "}
  //       <HomeWrapper>{children}</HomeWrapper>
  //     </body>
  //   </html>
  // );

  // return (
  //   <html lang="en">
  //     <body className={inter.className}>
  //       <CartProviderWrapper>
  //         {children}
  //       </CartProviderWrapper>
  //     </body>
  //   </html>
  // );

  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersWrapper>
          <div className="bg-gray-50 w-full min-h-screen">{children}</div>
        </ProvidersWrapper>
      </body>
    </html>
  );
}
