# fly.toml app configuration file generated for eternolux-nameless-river-6265 on 2026-01-26T21:27:56-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'eternolux-nameless-river-6265'
primary_region = 'dfw'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
